# Generated by Django 5.2.5 on 2025-08-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(choices=[('EN', 'English'), ('HI', 'Hindi')], default='EN', max_length=2),
        ),
    ]
